---
title: USS classification
author: Dominic Pearce
output:
    github_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.align = 'center')
```

```{r}
library(tidyverse)
library(ggthemes)
```

```{r}
uss_dfr <- read.csv("../../output/uss-clin.csv")

head(uss_dfr[uss_dfr$is_uss,])

dormant_dfr <- lapply(unique(uss_dfr$patient_id), function(patient){
                          #subset by patient
                          int_dfr <- uss_dfr[uss_dfr$is_uss & uss_dfr$patient_id == patient,]
                          ord_dfr <- int_dfr[order(int_dfr$days_treated),]
                          #split into pre- and post-90 day subset
                          pre3 <- ord_dfr[ord_dfr$days_treated <= 90, ]
                          post3 <- ord_dfr[ord_dfr$days_treated > 90, ]
                          #if there is a pre-90 day volume decrease by at least 40% & any 
                          #subsequent increase, relative to the lowest pre-90 measurement, 
                          #of >=5% then it's desensitised, else it's dormant. If there is no
                          #pre-90 day decrease then it is excluded from the study

                          if(any(!pre3$relative_vol <= 60)){
                              FALSE
                          } else if()

    ord_dfr[-c(1:(which(ord_dfr$relative_vol <= 60)-1)),]

                          data.frame(is_dormant = all(any(pre3$relative_vol <= 60) &
                                                       any(max(post3$relative_vol) -
                                                           min(pre3$relative_vol) <= -5)),
                                     patient_id = patient)
}) %>% do.call(rbind, .) %>% na.omit

ussdorm_dfr <- merge(dormant_dfr, uss_dfr, by = 'patient_id') 

ggplot(ussdorm_dfr, aes(x = days_treated, 
                        y = relative_vol, 
                        group = patient_id, 
                        colour = is_dormant)) + 
    geom_hline(yintercept = 60, linetype = 3) + 
    geom_line() + 
    theme_pander()

ggplot(ussdorm_dfr, aes(x = as.character(patient_id), y = days_treated)) +
    geom_point(colour = "#1f78b4", alpha = 0.5, data = ussdorm_dfr[ussdorm_dfr$is_uss,]) + #blue
    geom_point(colour = "#e31a1c", alpha = 0.5, data = ussdorm_dfr[ussdorm_dfr$is_biopsy,]) #red

```
