---
title: Dormancy Subtyping
author: Dominic Pearce
output:
    github_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.align = 'center')
```

```{r}
library(tidyverse)
library(transcripTools)
library(genefu)
library(AIMS)
library(pamr)
library(Biobase)
library(ggthemes)
library(cowplot); theme_set(theme_grey())
```

```{r}
edset <- read_rds("../output/edset-organised.rds")
edset$is_dormant <- ifelse(edset$is_dormant, "Dormant", "Desensitised")
edset$treatment <- Hmisc::capitalize(edset$treatment)
```

## Convert to entrezgene ids (genefu requires this) and package as a new edset

```{r}
xpr_entrez <- idReplace(exprs(edset), id.in = "hgnc_symbol", id.out = "entrezgene")
phenoData <- new("AnnotatedDataFrame", data = pData(edset),  varMetadata = varMetadata(edset))
edset_entrez <- new("ExpressionSet", exprs = as.matrix(xpr_entrez), phenoData = phenoData)
```

## Calculate subtypes

```{r}
ano_dfr <- data.frame(probe = row.names(edset_entrez), 
                      EntrezGene.ID = row.names(edset_entrez), 
                      rownames = row.names(edset_entrez))

preds_base <- data.frame(pred = intrinsic.cluster.predict(pam50, 
                                                          t(exprs(edset_entrez)), 
                                                          ano_dfr, do.mapping = TRUE)$subtype,
                         method = "pam50")
preds_base$sample <- row.names(preds_base)
row.names(preds) <- NULL
```

### As some samples have multiple biopsies within the same window (on-, long-term etc) we need to remove one them. 

```{r}
preds <-  preds_base[which(!grepl("e", preds_base$sample)),]

gsub("-.", "", preds$sample) %>% unique %>% length

```

## Combine with phenoData

```{r}
preds_mrg <- merge(preds, pData(edset_entrez), by.x = "sample", by.y = "sample_id")
#preds_mrg$timep <- ifelse(preds_mrg$time.point_3cat == 1, "Diagnosis", ifelse(preds_mrg$time.point_3cat == 2, "On-treatment", "Long-term"))
preds_mrg$time_tile <- factor(preds_mrg$treatment, levels = c("Extended", "Early", "Diagnostic"))
preds_mrg$time_hist <- factor(preds_mrg$treatment, levels = c("Diagnostic", "Early", "Extended"))

#order by time to final biopsy
tmp <- lapply(unique(preds_mrg$patient_id), function(p){
                  dfr <- preds_mrg[preds_mrg$patient_id == p,]
                  dfr[nrow(dfr),]
             }) %>% do.call(rbind, .)
preds_mrg$patient_id <- factor(preds_mrg$patient_id, levels = tmp$patient_id[order(tmp$time_treated)])

write.csv(preds_mrg, "/Volumes/igmm/sims-lab/Dominic/writing/PhD/thesis/data/results/dormancy/subtyping-dfr.csv")

p_tile <- ggplot(preds_mrg, aes(patient_id, y = time_tile, fill = pred)) + 
    geom_tile(width = 1, colour = "WHITE") + 
    scale_fill_manual(values=c("#1f78b4", "#a6cee3", "#fb9a99", "#e31a1c", "#b2df8a"), 
                    limits=c("LumA", "LumB", "Her2", "Basal", "Normal")) +
    facet_grid(~is_dormant, scales = 'free', space = 'free') +
    labs(fill = "Subtype") + 
    ggthemes::theme_pander() + 
    theme(axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          panel.spacing.x = unit(1.25, "lines"),
          legend.position = "bottom")
p_tile
#ggsave("../figs/pam50-subtypes.png")
```

## Display the relative change in subtypes as histogram?

```{r}
p_hist <- ggplot(preds_mrg[preds_mrg$method == "pam50",], aes(x = pred, fill = pred)) + 
    geom_histogram(stat = 'count') + 
    scale_fill_manual(values=c("#1f78b4", "#a6cee3", "#fb9a99", "#e31a1c", "#b2df8a"), 
                    limits=c("LumA", "LumB", "Her2", "Basal", "Normal")) +
    theme_pander() + 
    theme(legend.position = 'none') + 
    facet_grid(is_dormant ~ time_hist)
p_hist
```

## Combine

```{r}
plot_grid(p_tile, p_hist, ncol = 1, rel_heights = c(1, 2), scale = 0.98)
#ggsave("../figs/pam50-subtypes.png")
```

## Cigdem wanted the numbers of each subtype at diagnosis

```{r}

diag_subtypes <- sapply(c("D", "ND"), function(x){
                            table(preds_mrg[which(preds_mrg$timep == "Diagnosis" &
                                                  preds_mrg$dorm.group_v4 == x),]$pred)
                    }) %>% data.frame
#write_csv(diag_subtypes, "../output/diagnostic-subtype-distribution.csv")
```
