---
title: Georgetown Pre-processing
author: Dominic Pearce
output:
    github_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.align = 'center',
                      eval = FALSE)
```

```{r, eval = TRUE}
library(affy)
library(tidyverse)
library(Biobase)
library(frma)
library(hgu133plus2frmavecs)
library(knitr)
library(a4Base)
```

## First we'll read in our .cel files in batch, normalise using frma, feature select and loess normalise - though not necessarily in that order! 

#### Create AffyBatch from .CEL files

```{r, eval = FALSE}
dir_vec <- c("../data/Edinburgh\ Second\ Batch\ 170\ Samples/ff",
             "../data/Edinburgh\ Second\ Batch\ 170\ Samples/ffpe")

affybatch_lst <- lapply(dir_vec, function(dir){
                            setwd(dir)
                            affybatch <- ReadAffy()
                            setwd("../../../src")
                            affybatch
             })
```

#### Feature selection

```{r, eval = FALSE}
goodcalls_lst <- lapply(affybatch_lst, function(batch){
                            #get present, marginal, absent calls
                            ap <- mas5calls(batch)
                            #for each gene check that it not called absent in less than 90% of samples
                            goodcalls <- rowSums(exprs(ap) != "A") > (ncol(ap) / 10)
                            row.names(ap)[which(goodcalls)]
             })
#retreive common probes and write out
present_common <- do.call(intersect, goodcalls_lst)

```

```{r, echo = FALSE}
write_rds(goodcalls_lst, "../output/goodcalls-lst.rds")
goodcalls_lst <- read_rds("../output/goodcalls-lst.Rds")
#writeLines(present_common, "../output/present-probeset.txt")
present_common <- readLines("../output/present-probeset.txt")
```

```{r, eval = TRUE}
data.frame(present_10 = c(length(goodcalls_lst[[1]]), 
                          length(goodcalls_lst[[2]]), 
                          length(present_common)),
           material = c("FF", "FFPE", "Common")
           ) %>% knitr::kable()
```

#### 2-step normalisation - frma and loess 

```{r, eval = FALSE}
data(hgu133plus2frmavecs)
frma_lst <- lapply(affybatch_lst, function(batch){
                       batch_frma <- frma(batch, input.vecs = hgu133plus2frmavecs)  
                       batch_frma[present_common, ]
           })
#georgeset <- do.call(Biobase::combine, frma_lst)
#write_rds(georgeset, "~/Desktop/temp-store/georgeset-sep-frma-fselect.rds")


norm_lst <- lapply(frma_lst, function(batch){
                       mtx <- normalize.loess(exprs(batch))
                       exprs(batch) <- mtx
                       batch
           })
georgeset <- do.call(Biobase::combine, norm_lst)
#write_rds(georgeset, "~/Desktop/temp-store/georgeset-sep-frma-fselect-loess.rds")
```
