---
title: Unsupervised Analysis
author: Dominic Pearce
output:
    github_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.align = 'center', 
                      fig.width = 9)
```

```{r}
library(tidyverse)
library(Biobase)
library(ggthemes)
library(cowplot); theme_set(theme_grey())
source("/Volumes/igmm/sims-lab/Dominic/functions/idReplace.R")
source("/Volumes/igmm/sims-lab/Dominic/functions/mostVar.R")
source("/Volumes/igmm/sims-lab/Dominic/functions/library/mdsArrange.R")
source("/Volumes/igmm/sims-lab/Dominic/functions/library/tsneArrange.R")
```


<!--
//TODO try using only A, B, C samples to see if they sit close to one another

//TODO you were in the middle of t-sneifying but when you're running the first implementation since you added the perplexity argument the plot looks different each time
-->

```{r}
dormset <- read_rds("../output/dormset.rds")
pData(dormset)[dormset$patient == 343,]$is_dormant <- TRUE
pData(dormset)[dormset$patient == 374,]$is_dormant <- TRUE
```

```{r}
## T-SNE playing 
eset <- lt_500#[, which(lt_500$timepoint == "long-term")]

arng_dfr <- mdsArrange(exprs(eset))
mrg_dfr <- merge(arng_dfr, pData(eset), by.x = 'ids', by.y = 'xpr_id')

mtx <- eset %>% exprs() %>% t()
set.seed(42) # Set a seed if you want reproducible results

tsne_out <- tsneArrange(mtx)
tsne_mrg <- merge(tsne_out, pData(eset), by = 'xpr_id')
ggplot(tsne_mrg, aes(x = X1, y = X2, colour = is_dormant, label = sample_id)) + 
        geom_text() + 
        theme(legend.position = 'none')

ggplot(mrg_dfr, aes(x = x, y = y, colour = patient)) + 
    geom_point() 

```





#### as well as how well the are able to cluster patients based on dormancy status

```{r}
plotSNE <- function(eset, time_point = "all", title = "", perplexity = 30){
    if(time_point[[1]] != "all"){
               eset_in = eset[, which(eset$timepoint %in% time_point)]
           } else {
               eset_in = eset 
           }
    arng_dfr <- tsneArrange(t(exprs(eset_in)), perplexity = perplexity)
    mrg_dfr <- merge(arng_dfr, pData(eset_in), by = 'xpr_id')
    
    p_sne <- ggplot(mrg_dfr, aes(x = X1, y = X2, colour = is_dormant, label = sample_id)) + 
        geom_text() + 
        labs(title = title,
             subtitle = paste0("x separation p = ", 
                               wilcox.test(X1~is_dormant, data = mrg_dfr)$p.value)) +
        theme_pander() +
        theme(legend.position = 'top')

    p_sne
#    p_box <- ggplot(mrg_dfr, aes(x = is_dormant, y = X1, fill = is_dormant)) + 
#        geom_boxplot(notch = TRUE) + 
#        coord_flip() + 
#        theme_pander() + 
#        theme(legend.position = 'none')
#    plot_grid(p_mds, p_box, rel_heights = c(3, 1), ncol = 1)
}
```

#### We can calculate the 500 most-variable genes independently for long-term treated and untreated samples, as well as finding the cross-over and outersect of these genesets.

```{r}
getTimepoint500 <- function(timepoint){
        dormset_sub <- dormset[, which(dormset$timepoint == timepoint)]
        mv500 <- mostVar(exprs(dormset_sub), 500) %>% row.names()
        dormset[mv500,]
}

lt_500 <- getTimepoint500("long-term") 
pre_500 <- getTimepoint500("diagnosis")

common <- intersect(row.names(lt_500), row.names(pre_500))
common_327 <- dormset[common, ]

lt_common <- which(row.names(lt_500) %in% common)
lt_unique <- row.names(lt_500)[-lt_common]
ltu_173 <- dormset[lt_unique, ]

pre_common <- which(row.names(pre_500) %in% common)
pre_unique <- row.names(pre_500)[-pre_common]   
preu_173 <- dormset[pre_unique, ]
```


### Long-term 500

```{r}
plotSNE(lt_500, 'all', 'All Samples')
plotSNE(lt_500, c('on-treatment', 'long-term'), 'Treated Samples')
plotSNE(lt_500, 'long-term', 'Long-term Samples')
plotSNE(lt_500, 'on-treatment', 'On-treatment Samples')
plotSNE(lt_500, 'diagnosis', 'Diagnostic Samples')
```

### Pre-treatment 500

```{r}
plotSNE(pre_500, 'all', 'All Samples')
plotSNE(pre_500, c('on-treatment', 'long-term'), 'Treated Samples')
plotSNE(pre_500, 'long-term', 'Long-term Samples')
plotSNE(pre_500, 'on-treatment', 'On-treatment Samples')
plotSNE(pre_500, 'diagnosis', 'Diagnostic Samples')
```

### Intersect 327

```{r}
plotSNE(common_327, 'all', 'All Samples')
plotSNE(common_327, c('on-treatment', 'long-term'), 'Treated Samples')
plotSNE(common_327, 'long-term', 'Long-term Samples')
plotSNE(common_327, 'on-treatment', 'On-treatment Samples')
plotSNE(common_327, 'diagnosis', 'Diagnostic Samples')
```

### Long-term unique 173

```{r}
plotSNE(ltu_173, 'all', 'All Samples')
plotSNE(ltu_173, c('on-treatment', 'long-term'), 'Treated Samples')
plotSNE(ltu_173, 'long-term', 'Long-term Samples')
plotSNE(ltu_173, 'on-treatment', 'On-treatment Samples')
plotSNE(ltu_173, 'diagnosis', 'Diagnostic Samples')
```

### Pre-treatment unique 173

```{r}
plotSNE(preu_173, 'all', 'All Samples')
plotSNE(preu_173, c('on-treatment', 'long-term'), 'Treated Samples')
plotSNE(preu_173, 'long-term', 'Long-term Samples')
plotSNE(preu_173, 'on-treatment', 'On-treatment Samples')
plotSNE(preu_173, 'diagnosis', 'Diagnostic Samples')
```
